config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#pres'

  devise_for :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :spots, only: [:show]

  resources :favorites, only: [:index]
  resources :activities do
    post "/toggle", to: "favorites#toggle_favorite"
    resources :participations, except: [:index]
  end

  get '/dashboard', to: 'pages#dashboard'
  get '/video', to: 'pages#video'

  get '/profile', to: 'pages#profile'

  resources :contacts, only: [:new, :create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :activity
  belongs_to :user
  belongs_to :contact
end

app/controllers/participations_controller.rb
require 'twilio-ruby'

class ParticipationsController < ApplicationController
  before_action :set_activity, only: [:new, :create, :show, :update]
  before_action :set_participation, only: [:destroy, :update, :show]

  def new
    @user = current_user
    @participation = Participation.new
    @participation.start = @activity.date_time_start
    @participation.end = @activity.date_time_end
    @contacts = Contact.where(user: current_user)
    # authorize @participation
  end

  def show
  end

  def send_sms_to_contact
    account_sid = ENV['TWILIO_ACCOUNT_SID']
    auth_token = ENV['TWILIO_AUTH_TOKEN']
    @client = Twilio::REST::Client.new(account_sid, auth_token)

    message = @client.messages.create(
      body: "#{@participation.user.name} surf le #{@participation.activity.date_time_start.strftime("%d/%m/%Y")}
de #{@participation.start.strftime("%Hh%M")}
à #{@participation.end.strftime("%Hh%M")}
à #{@participation.activity.spot.name}
avec #{@activity.participations_count} buddies",
      from: '+12512577944',
      to: "+33#{@participation.contact.tel}}"
    )
  end

  def sms_rappel
    @user = current_user
    account_sid = ENV['TWILIO_ACCOUNT_SID']
    auth_token = ENV['TWILIO_AUTH_TOKEN']
    @client = Twilio::REST::Client.new(account_sid, auth_token)

    message = @client.messages.create(
      body: "#{@participation.contact.name} est prévenu de ton départ en session. Pense à le prévenir quand tu seras rentrée. Bon surf !",
      from: '+12512577944',
      to: "+33#{@user.tel}}"
    )
  end


  def send_sms_back
    TwillioMessage.send_sms("#{@participation.user.name} est bien rentrée de sa session", "+33#{@participation.contact.tel}")
  end

  def sms_confirmation
    TwillioMessage.send_sms("#{@participation.contact.name} a bien été prévenu de ton retour de session", "+33#{@user.tel}")
  end

  def create
    @participation = Participation.new(participation_params)
    @participation.activity = @activity
    @participation.user = current_user
    if @participation.save!
      send_sms_to_contact
      sms_rappel
      redirect_to activity_participation_path(@activity, @participation)
    else
      :new
    end
    # authorize @participation
  end

  # def index
  #   @participations = Participation.all
  # end

  def edit
    # authorize @participation
  end

  def update
    @participation.status = true
    @user = current_user
    # @order.user = current_user
    send_sms_back
    sms_confirmation
    puts current_user
    puts current_user.score
    current_user.score += @participation.activity.min_score
    puts current_user.score
    current_user.save!
    @participation.save!
    redirect_to dashboard_path
  end

  def destroy
    @participation.user = current_user
    @participation.destroy
    redirect_to dashboard_path
    # authorize @participation
  end

  # def status
  #   @participation.status = !@participation.status
  #   @participation.save
  #   redirect_to dashboard_path
  # end

  private

  def set_participation
    @participation = Participation.find(params[:id])
  end

  def set_activity
    @activity = Activity.find(params[:activity_id])
  end

  def participation_params
    params.require(:participation).permit(:start, :end, :user_id, :activity_id, :contact_id, :completed)
  end
end

app/views/participations/_form.erb
<div style="display: flex;flex-direction: column">
  <div class="session_form">
    <%= simple_form_for([@activity, @participation]) do |f| %>
      <%= f.input :start, as: :time, :label => "Heure de début :" %>
      <%= f.input :end, as: :time, :label => "Heure de fin :" %>
      <%= f.input :contact_id, :label => "Choisir mon contact d'urgence :", :collection => @contacts %>
      <div class="btns">
        <%= f.submit "Confirmer" %>
          <%= link_to 'Back', onclick: "window.history.back();", id: "icone-arrow" do %>
            <h2 class="btn-small" >Back</h2>
          <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/participations/new.html.erb
<div class="participation">

  <div class="background_image">

    <div class="participation_title">
      <h1> Planifier ma session </h1>
      <h3>Du <%= @activity.date_time_start.strftime("%d/%m/%Y")%></h3>
    </div>

    <div class="participation_form">
      <%= render "participations/form" %>

    </div>
  </div>


</div>

app/views/participations/show.html.erb
<div class="show-participation">

  <div class="banner">
    <div class="participation-content">
      <h1>Profite de ta session !</h1>
      <%= link_to video_path do %>
        <h3><%= @participation.contact.name %> a été notifié le <%= @participation.start.strftime("%d/%m/%Y à %Hh%M")%> de ton départ en session ! Pense à le prévenir à ton retour. Il recevra un nouveau message si tu n'as pas validé la fin de ta session.</h3>
      <% end %>
    </div>
  </div>
<%= render 'shared/navbar' %>
</div>