config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#pres'

  devise_for :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :spots, only: [:show]

  resources :favorites, only: [:index]
  resources :activities do
    post "/toggle", to: "favorites#toggle_favorite"
    resources :participations, except: [:index]
  end

  get '/dashboard', to: 'pages#dashboard'
  get '/video', to: 'pages#video'

  get '/profile', to: 'pages#profile'

  resources :contacts, only: [:new, :create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_favoris.html.erb
<div class="session-favorites" data-action="click->favorites#favorise" data-favorites-target="favoris">
  <% if current_user.favorite_for(activity) %>
    <span class="iconify" style="color:#f573b2" data-icon="bi:heart-fill"></span>
  <% else %>
    <span class="iconify" data-icon="bi:heart">heart</span>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar">

  <div class="navbar-btn" >
    <a href="/activities"><span class="iconify" data-icon="bi:search">sessions</span></a>
    <label>sessions</label>
  </div>

  <div class="navbar-btn" >
    <a href="/favorites"><span class="iconify" data-icon="akar-icons:heart"></span></a>
    <label>favoris</label>
  </div>

  <div class="navbar-btn">
    <a href="/dashboard"><span class="iconify" data-icon="carbon:wave-height">dashboard</span></a>
    <label>dashboard</label>
  </div>

  <div class="navbar-btn">
    <a href="/profile">
    <span class="iconify" data-icon="iconoir:profile-circled"></span></a>
    <label>profil</label>
  </div>

</div>

app/views/shared/_participation_card.html.erb
<div class="participation-card" style="background-image: url(<%= participation.activity.spot.photo.attached? ? cl_image_path(participation.activity.spot.photo.key) : asset_path("surfer.jpg") %>)">
  <% if participation.status? %>
    <h1>Session du <%= participation.activity.date_time_start.strftime("%d/%m/%Y à %Hh%M")%></h1>
    <h2><%= participation.contact.name %> a bien été prévenu !</h2>
      <div class="session-terminee sms-envoye">
        <span class="iconify text-sms" data-icon="bi:check-lg"></span>
        <h3 class="text-sms">SMS envoyé</h3>
      </div>
  <% else %>
      <h1>Session du <%= participation.start.strftime("%d/%m/%Y à %Hh %M")%></h1>
      <h2>Préviens <%= participation.contact.name %> que ta session est terminée !</h2>
    <%= link_to activity_participation_path(participation.activity, participation), method: :patch, remote: true do %>
      <div class="session-terminee">
        <h3 class="text-terminee">session terminée !</h3>
      </div>
    <% end %>
  <% end %>


  <%= link_to activity_path(participation.activity) do%>
  <div class="show-session-btn">
    <h3 class="text-session">voir la session</h3>
  </div>
  <% end %>
</div>

app/views/shared/_session_card.html.erb
<div class="controller-favorites" data-controller="favorites">
<div class="session-card" >
  <div class="session-image" style="background-image: url(<%= activity.spot.photo.attached? ? cl_image_path(activity.spot.photo.key) : asset_path("surfer.jpg") %>)">
    <%= link_to activity_path(activity),  data: { favorites_target: "link" }, remote: true do %>
      <%= link_to activity_path(activity) do %>
      <div class="session-left">
        <div class="categorie-session">
          <span class="iconify" data-icon="arcticons:weather">soleil</span>
          <h6><%= activity.temp %>°</h6>
        </div>
        <div class="categorie-session">
          <span class="iconify" data-icon="carbon:temperature-water">eau</span>
          <h6><%= activity.water_temp %>°</h6>
        </div>
        <div class="categorie-session">
          <span class="iconify" data-icon="map:surfing">surfer</span>
          <h6><%= activity.participations_count %></h6>
        </div>
        <div class="categorie-session">
          <% waves_number = activity.wave_height * 2 %>
          <% waves_number.times do %>
            <span class="iconify" data-icon="carbon:wave-height">wave</span>
          <% end %>
        </div>
      </div>
      <% end %>
    <% end %>
    <div class="session-right">
      <%= render 'shared/favoris', activity: activity %>
      <div class="session-flag">
        <% flag_color = activity.flag.downcase %>
        <% if flag_color == "green" %>
          <span class="iconify" data-icon="ooui:flag-rtl" style="color:#4CED52">flag</span>
        <% elsif flag_color == "yellow" %>
          <span class="iconify" data-icon="ooui:flag-rtl" style="color:#ffea00">flag</span>
        <% else  %>
          <span class="iconify" data-icon="ooui:flag-rtl" style="color:red">flag</span>
        <% end %>
      </div>
    </div>
  </div>
  <div class="session-bottom">
    <% months = ["Janvier", "Février", "Mars", "Avril", "Mai" , "Juin", "Juillet" , "Aout" , "Septembre", "Octobre", "Novembre", "Décembre"] %>
    <p> <%= activity.date_time_start.day %> &nbsp;</p>
    <p> <%= months[activity.date_time_start.month - 1] %> &nbsp;</p>
    <span class="pink"> ● &nbsp;</span>
    <p> <%=  %> <%= activity.spot.name %> &nbsp;</p>
  </div>
</div>
</div>