config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#pres'

  devise_for :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :spots, only: [:show]

  resources :favorites, only: [:index]
  resources :activities do
    post "/toggle", to: "favorites#toggle_favorite"
    resources :participations, except: [:index]
  end

  get '/dashboard', to: 'pages#dashboard'
  get '/video', to: 'pages#video'

  get '/profile', to: 'pages#profile'

  resources :contacts, only: [:new, :create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/dashboard.html.erb
<% require 'date' %>

<div class="dashboard">
  <div class="top">
    <h1>Dashboard de <span class="highlight"><%= @user.name %></span></h1>
  </div>
  <div class="incoming">
    <h3 class="main-title">Sessions à ce jour: <span class="highlight"><%= @my_future_participations.count %></span></h3>
  <% @my_future_participations.each do |participation| %>
    <%= render 'shared/participation_card', participation: participation %>
  <% end %>
  </div>
  <div class="score">
    <h1>Score : <span id="score"><%= current_user.score %></span></h1>
  </div>
  <%= render 'shared/navbar' %>
</div>

app/views/pages/home.html.erb
<h1>Take Off</h1>
<h2>salut</h2>

<%= render 'shared/navbar' %>
<%= link_to"Les sessions" , activities_path %>
<%= link_to"Le dashboard" , dashboard_path %>
<%= link_to"Admin Panel" ,  rails_admin_path %>

app/views/pages/pres.html.erb
<div class="pres-page" style="background-image: url(<%= asset_path("home-take-off.gif") %>)">
  <%= link_to "log in", activities_path, id: "btn-login-pres" %>
</div>

app/views/pages/profile.html.erb
<div class="profile">
  <div class="background_edit">
    <div class="mon-profil">
      <div class="mon-profil-header">
      <h1> Mon profil </h1>
      </div>
    </div>

    <div class="user-picture-name">
        <img class="avatar" alt="avatar" src="https://scontent.fcdg4-1.fna.fbcdn.net/v/t1.18169-9/14040100_1659643937684783_7350282897754591794_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=174925&_nc_ohc=7cTzhCBNIawAX92hei6&_nc_ht=scontent.fcdg4-1.fna&oh=00_AT_5BqrcJLjzEpv8bUqwVxPD-ONbkQgEW-svVEwEbw2o4Q&oe=62D6A069" />
        <div class="name">
          <h2> <%= @user.name %> </h2>
          <p> 0<%= @user.tel %> </p>
          <p> <%= @user.email %> </p>
          <p> Niveau intermédiaire </p>
          <div class="form-actions-1">
            <%= link_to "Modifier", edit_user_registration_path %>
          </div>
        </div>
    </div>

    <div class="title-contact">
      <div class="title-contact-header">
      <h1> Mes contacts d'urgence </h1>
      </div>
    </div>

    <div class="contact-1">
      <div class="contact">
        <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false">
          <div class="carousel-indicators d-none">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
          </div>
          <div class="carousel-inner">
            <% @contacts.each_with_index do |contact, index| %>
              <% if index == 0 %>
                <div class="box-name carousel-item active">
                  <p> <%= contact.name %> <p>
                  <p>0<%= contact.tel %> <p>
                </div>
              <% else %>
                <div class="box-name carousel-item">
                  <p> <%= contact.name %> <p>
                  <p>0<%= contact.tel %> <p>
                </div>
              <% end %>
            <% end %>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
        <div class="form-box">
        <%= link_to new_contact_path do %>
          <span class="iconify surf" data-icon="ant-design:plus-circle-outlined"></span>
        <% end %>
        </div>
      </div>
    </div>
    <div class="log-out">
      <div class="btn">
        <a id="btn-logout" rel="nofollow" data-method="delete" href="/users/sign_out">Déconnexion</a>
      </div>
    </div>
    <%= render 'shared/navbar' %>
  </div>
</div>

app/views/pages/video.html.erb
<div class="pres-page" style="background-image: url(<%= asset_path("session.gif") %>)">
<h1 class="title">Session en cours </h1>
<%= link_to "sortir de l'eau", dashboard_path, id: "btn-login" %>
</div>
<style>

</style>