config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#pres'

  devise_for :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :spots, only: [:show]

  resources :favorites, only: [:index]
  resources :activities do
    post "/toggle", to: "favorites#toggle_favorite"
    resources :participations, except: [:index]
  end

  get '/dashboard', to: 'pages#dashboard'
  get '/video', to: 'pages#video'

  get '/profile', to: 'pages#profile'

  resources :contacts, only: [:new, :create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :spot
  has_many :participations, dependent: :destroy
  has_many :favorites

  def participations_count
    @participations = self.participations.count
  end

  include PgSearch::Model
  pg_search_scope :search,
    against: [ :name],
    associated_against: {
      spot: [ :name, :address ]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :get_participations, only: [:show, :index]

  def new
    @activity = Activity.new
    @spots = Spot.all
    @flags = ["Green", "Yellow", "red"]
  end

  def create
    @activity = Activity.new(activity_params)
    if activity.save
      redirect_to activity_path(@activity)
    else
      :new
    end
  end

  def index
    @activities = Activity.all.order("date_time_start ASC")
    @user = current_user
    @markers = @activities.map do |activity|
      {
        lat: activity.spot.latitude,
        lng: activity.spot.longitude,
        info_window: render_to_string(partial: "info_window", locals: { activity: activity }),
        image_url: helpers.asset_url("logo-surfapp.png")
      }
    end
    if params[:query].present?
      @activities = Activity.search(params[:query])
    else
      @activities
    end
  end

  def show
    @wetsuit = ""
    wetsuits = ["Shorty", "3/2", "4/3", "5/4"]
    if @activity.water_temp < 12
      @wetsuit = wetsuits[3]
    elsif @activity.water_temp > 12 && @activity.water_temp < 17
      @wetsuit = wetsuits[2]
    elsif @activity.water_temp > 17 && @activity.water_temp < 22
      @wetsuit = wetsuits[1]
    else
      @wetsuit = wetsuits[0]
    end
  end

  def edit
  end

  def update
    @activity.update(activity_params)
  end

  def destroy
    @activity.destroy
  end

  private

  def set_activity
    @activity = Activity.find(params[:id])
  end

  def activity_params
    params.require(:activity).permit(:wave_height, :wind, :period, :wind_direction, :wave_direction, :min_score, :date_time_start, :date_time_end, :tips, :photo, :spot )
  end

  def get_participations
    @participations = Participation.includes(:user).where(activity: @activity)
  end
end

app/views/activities/_form.html.erb
<%= simple_form_for @activity do |f| %>
  <%= f.input :wave_height, as: :float, placeholder: "Entrer la hauteur des vagues" %>
  <%= f.input :wind, as: :integer, placeholder: "Entrer la vitesse du vent" %>
  <%= f.input :flag, placeholder: "Entrer le drapeau" %>
  <%= f.input :period, as: :float, placeholder: "Entrer la période" %>
  <%= f.input :wind_direction, placeholder: "Entrer la dirction du vent", :collection => %w[N NE E SE S SW W NW] %>
  <%= f.input :wave_direction, placeholder: 'Entrer la direction des vagues', :collection => %w[N NE E SE S SW W NW] %>
  <%= f.input :min_score, as: :numeric, placeholder: 'Entrer le score minimum' %>
  <%= f.input :date_time_start %>
  <%= f.input :date_time_end %>
  <%= f.input :tips, as: :text, placeholder: "Entrer les tips" %>

  <%= f.input :spot_id, placeholder: "Entrer le spot", :collection => @spots %>

  <%= f.submit "Créer" %>
<% end %>

app/views/activities/_info_window.html.erb
<%= link_to activity_path(activity) do %>
  <h2><%= activity.name %></h2>
<% end %>
<p><%= activity.spot.address %></p>

app/views/activities/index.html.erb
<div class="sessions-index" data-controller="index">
    <div class="main-title-session">
        <h2>Aloha, <span class="highlight"><%= @user.name %> ! </span></h2>
        <br>
        <p> Découvre les spots adaptés à ton niveau cette semaine ! </p>
    </div>
  <div class="map" style="width: 100%; height: 100vh;"
    data-controller="mapbox"
    data-mapbox-markers-value="<%= @markers.to_json %>"
    data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

  <div class="cards-container" data-index-target="cardcontainer">
    <div class="swipe-up" data-action="click->index#swipeup" data-index-target="swipeup"></div>
    <div class="scroll-container">
      <h3>Nous avons créé <font color= "#FF1569"><strong><%= @activities.count %></strong></font> sessions</h3>
      <div class="card-sessions-container">
          <% @activities.each do |activity| %>
              <%= render 'shared/session_card', activity: activity %>
          <% end %>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/navbar' %>

app/views/activities/new.html.erb
<h1 class="">Add a new offer</h1>
<div class="">
  <%= render "form" %>
</div>

app/views/activities/show.html.erb
<div class= show-session >
  <div class="banner" style="background-image: url(<%= @activity.spot.photo.attached? ? cl_image_path(@activity.spot.photo.key) : image_tag("surfer.jpg") %>)">
    <div class="container">
      <h1>Session</h1>
      <h2><%= @activity.spot.name %></h2>
    <div class="btn-spot">
      <%= link_to "Afficher le spot", spot_path(@activity.spot.id), class: "btn-big" %>
    </div>
    </div>
  </div>



  <div class= "session-details">
    <div class="session-content">

      <div class="session-div">
        <span class="iconify" data-icon="carbon:wave-height"></span>
        <p>Environ <strong><%= @activity.wave_height %>m</strong> de vague</p>
      </div>

      <div class="session-div">
              <span class="iconify" data-icon="raphael:temp"></span>
              <p>Air: <strong><%= @activity.temp %>°C</strong></p>
            </div>

      <div class="session-div">
        <span class="iconify" data-icon="ion:shirt"></span>
        <p>Eau: <strong><%= @activity.water_temp %>°C</strong><br>Combinaison recommandée: <strong><%= @wetsuit %></strong></p>
      </div>

      <div class="session-div">
        <% flag_color = @activity.flag.downcase %>
        <% if flag_color == "green" %>
          <span class="iconify" data-icon="ooui:flag-rtl" style="color:#4CED52">flag</span>
          <p>Conditions idéales !</p>
        <% elsif flag_color == "yellow" %>
          <span class="iconify" data-icon="ooui:flag-rtl" style="color:#ffea00">flag</span>
          <p>Danger potentiel, restez sur vos gardes</p>
        <% else  %>
          <span class="iconify" data-icon="ooui:flag-rtl" style="color:red">flag</span>
          <p>Surfez à vos risques et périls </p>
        <% end %>
      </div>

      <div class="session-div">
        <span class="iconify" data-icon="bi:wind"></span>
        <p>Vent: <strong><%= @activity.wind %> nts</strong> </p>
      </div>

      <div class="session-div">
        <span class="iconify" data-icon="iconoir:sea-and-sun"></span>
        <p>Info marée: surfer entre <br> <strong><%= @activity.date_time_start.strftime('%Hh%M')%> et <%= @activity.date_time_end.strftime('%Hh%M')%></strong></p>
      </div>

      <div class="session-div">
        <span class="iconify" data-icon="carbon:wave-period"></span>
        <p>Période des vagues: <%= @activity.period %></strong></p>
      </div>

      <div class="session-div">
        <span class="iconify" data-icon="carbon:skill-level-basic"></span>
        <p>Niveau: <strong>moyen à confirmé</strong> </p>
      </div>

      <div class="session-div vertical">
        <span class="iconify" data-icon="clarity:info-standard-line"></span>
        <p><%= @activity.tips %>  </p>
      </div>

      <div class="session-div">
      </div>

      <div class= "buddies">
        <span class="iconify surf" data-icon="map:surfing"></span>
          <div class="avatars">
            <% if @participations.count == 0 %>
              <h2>Il n'y a pas encore de participants !</h2>
            <% else %>
              <% @participations.each do |participation| %>
                <%= participation.user.photo.attached? ? cl_image_tag(participation.user.photo.key, height: 40, width: 40, crop: :fill ) : image_tag("surfer.jpg")%>
              <% end %>
            <% end %>
          </div>
      </div>
    </div>

    <div class="btn-join-back">
      <%= link_to 'Retour', onclick: "window.history.back();", class: "btn-small" do %>
        <h2>Retour</h2>
      <% end %>
      <%= link_to "Rejoindre", new_activity_participation_path(@activity), class: "btn-join" %>
    </div>
  </div>
</div>